In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import r2_score
from sklearn.model_selection import GridSearchCV
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.metrics import RocCurveDisplay
import sklearn.metrics as metrics
import time
pd.set_option('display.max_columns', None)

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/CSV/Tree_Data.csv")

Dataset https://www.kaggle.com/datasets/yekenot/tree-survival-prediction

In [ ]:
df

,No,Plot,Subplot,Species,Light_ISF,Light_Cat,Core,Soil,Adult,Sterile,Conspecific,Myco,SoilMyco,PlantDate,AMF,EMF,Phenolics,Lignin,NSC,Census,Time,Event,Harvest,Alive
0,126,1,C,Acer saccharum,0.106,Med,2017,Prunus serotina,I,Non-Sterile,Heterospecific,AMF,AMF,6/11/18,22.00,NaN,-0.56,13.86,12.15,4,14.0,1.0,NaN,NaN
1,11,1,C,Quercus alba,0.106,Med,2017,Quercus rubra,970,Non-Sterile,Heterospecific,EMF,EMF,5/25/18,15.82,31.07,5.19,20.52,19.29,33,115.5,0.0,NaN,X
2,12,1,C,Quercus rubra,0.106,Med,2017,Prunus serotina,J,Non-Sterile,Heterospecific,EMF,AMF,5/31/18,24.45,28.19,3.36,24.74,15.01,18,63.0,1.0,NaN,NaN
3,2823,7,D,Acer saccharum,0.080,Med,2016,Prunus serotina,J,Non-Sterile,Heterospecific,AMF,AMF,6/11/18,22.23,NaN,-0.71,14.29,12.36,4,14.0,1.0,NaN,NaN
4,5679,14,A,Acer saccharum,0.060,Low,2017,Prunus serotina,689,Non-Sterile,Heterospecific,AMF,AMF,6/11/18,21.15,NaN,-0.58,10.85,11.20,4,14.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2778,7165,17,B,Prunus serotina,0.111,Med,2017,Populus grandidentata,891,Non-Sterile,Heterospecific,AMF,EMF,6/7/18,40.89,NaN,0.83,9.15,11.88,16,56.0,1.0,NaN,NaN
2779,7217,17,D,Quercus alba,0.118,Med,2017,Acer rubrum,1468,Non-Sterile,Heterospecific,EMF,AMF,5/25/18,15.47,32.82,4.88,19.01,23.50,16,56.0,1.0,NaN,NaN
2780,7306,17,D,Quercus alba,0.118,Med,2017,Quercus rubra,1454,Non-Sterile,Heterospecific,EMF,EMF,5/25/18,11.96,37.67,5.51,21.13,19.10,16,56.0,1.0,NaN,NaN
2781,7771,18,D,Quercus alba,0.161,High,2017,Sterile,1297,Sterile,Sterilized,EMF,Sterile,5/17/18,16.99,22.51,4.28,19.38,21.36,33,115.5,NaN,NaN,NaN
2782,7401,18,A,Prunus serotina,0.141,High,2016,Populus grandidentata,118,Non-Sterile,Heterospecific,AMF,EMF,6/7/18,60.46,NaN,1.00,9.04,11.82,16,56.0,1.0,NaN,NaN

In [ ]:
# Analisando os tipos de dados das colunas
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2783 entries, 0 to 2782
Data columns (total 24 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   No           2783 non-null   int64
 1   Plot         2783 non-null   int64
 2   Subplot      2783 non-null   object
 3   Species      2783 non-null   object
 4   Light_ISF    2783 non-null   float64
 5   Light_Cat    2783 non-null   object
 6   Core         2783 non-null   int64
 7   Soil         2783 non-null   object
 8   Adult        2783 non-null   object
 9   Sterile      2783 non-null   object
 10  Conspecific  2783 non-null   object
 11  Myco         2783 non-null   object
 12  SoilMyco     2783 non-null   object
 13  PlantDate    2783 non-null   object
 14  AMF          2783 non-null   float64
 15  EMF          1283 non-null   float64
 16  Phenolics    2783 non-null   float64
 17  Lignin       2783 non-null   float64
 18  NSC          2783 non-null   float64
 19  Census       2783 non-null   int64
 20  Time         2783 non-null   float64
 21  Event        2782 non-null   float64
 22  Harvest      704 non-null    object
 23  Alive        491 non-null    object
dtypes: float64(8), int64(4), object(12)
memory usage: 521.9+ KB

In [ ]:
#Quantidade de valores vazios em cada coluna
df.isna().sum()

No                0
Plot              0
Subplot           0
Species           0
Light_ISF         0
Light_Cat         0
Core              0
Soil              0
Adult             0
Sterile           0
Conspecific       0
Myco              0
SoilMyco          0
PlantDate         0
AMF               0
EMF            1500
Phenolics         0
Lignin            0
NSC               0
Census            0
Time              0
Event             1
Harvest        2079
Alive          2292
dtype: int64

In [ ]:
#Verificando a correlação entre as features
df.corr().style.background_gradient(cmap='Reds')

<ipython-input-7-b4d9d7f5051d>:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr().style.background_gradient(cmap='Reds')

In [ ]:
# Transformando as colunas String em colunas numericas
df_t2 = pd.get_dummies(df, columns=['Subplot', 'Species', 'Light_Cat', 'Soil', 'Adult', 'Sterile',
                                   'Conspecific', 'Myco', 'SoilMyco', 'PlantDate', 'Harvest', 'Alive'])

In [ ]:
df_t = df_t2.drop('No', axis=1)
df_t

,Plot,Light_ISF,Core,AMF,EMF,Phenolics,Lignin,NSC,Census,Time,Event,Subplot_A,Subplot_B,Subplot_C,Subplot_D,Subplot_E,Species_Acer saccharum,Species_Prunus serotina,Species_Quercus alba,Species_Quercus rubra,Light_Cat_High,Light_Cat_Low,Light_Cat_Med,Soil_Acer rubrum,Soil_Acer saccharum,Soil_Populus grandidentata,Soil_Prunus serotina,Soil_Quercus alba,Soil_Quercus rubra,Soil_Sterile,Adult_1027,Adult_118,Adult_1201,Adult_1205,Adult_1297,Adult_1320,Adult_1323,Adult_1326,Adult_1330,Adult_1332,Adult_1384,Adult_1386,Adult_1454,Adult_1468,Adult_1478,Adult_1595,Adult_1688,Adult_1715,Adult_1757,Adult_275,Adult_277,Adult_285,Adult_394,Adult_415,Adult_50,Adult_561,Adult_689,Adult_891,Adult_921,Adult_961,Adult_970,Adult_984,Adult_G,Adult_H,Adult_I,Adult_J,Sterile_Non-Sterile,Sterile_Sterile,Conspecific_Conspecific,Conspecific_Heterospecific,Conspecific_Sterilized,Myco_AMF,Myco_EMF,SoilMyco_AMF,SoilMyco_EMF,SoilMyco_Sterile,PlantDate_5/10/18,PlantDate_5/17/18,PlantDate_5/18/18,PlantDate_5/22/18,PlantDate_5/23/18,PlantDate_5/24/18,PlantDate_5/25/18,PlantDate_5/29/18,PlantDate_5/30/18,PlantDate_5/31/18,PlantDate_6/1/18,PlantDate_6/11/18,PlantDate_6/12/18,PlantDate_6/15/18,PlantDate_6/4/18,PlantDate_6/5/18,PlantDate_6/6/18,PlantDate_6/7/18,PlantDate_6/8/18,Harvest_X,Alive_X
0,1,0.106,2017,22.00,NaN,-0.56,13.86,12.15,4,14.0,1.0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
1,1,0.106,2017,15.82,31.07,5.19,20.52,19.29,33,115.5,0.0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,1,0.106,2017,24.45,28.19,3.36,24.74,15.01,18,63.0,1.0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
3,7,0.080,2016,22.23,NaN,-0.71,14.29,12.36,4,14.0,1.0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4,14,0.060,2017,21.15,NaN,-0.58,10.85,11.20,4,14.0,1.0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2778,17,0.111,2017,40.89,NaN,0.83,9.15,11.88,16,56.0,1.0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2779,17,0.118,2017,15.47,32.82,4.88,19.01,23.50,16,56.0,1.0,0,0,0,1,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2780,17,0.118,2017,11.96,37.67,5.51,21.13,19.10,16,56.0,1.0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2781,18,0.161,2017,16.99,22.51,4.28,19.38,21.36,33,115.5,NaN,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2782,18,0.141,2016,60.46,NaN,1.00,9.04,11.82,16,56.0,1.0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [ ]:
# Verificando quantidade de valores Vazios em cada coluna
df.isnull().sum()

No                0
Plot              0
Subplot           0
Species           0
Light_ISF         0
Light_Cat         0
Core              0
Soil              0
Adult             0
Sterile           0
Conspecific       0
Myco              0
SoilMyco          0
PlantDate         0
AMF               0
EMF            1500
Phenolics         0
Lignin            0
NSC               0
Census            0
Time              0
Event             1
Harvest        2079
Alive          2292
dtype: int64

In [ ]:
# Preenchendo os dados vazios da coluna EMF e da coluna Event
df_t['EMF'].fillna(df_t['EMF'].mean(), inplace=True)
df_t['Event'].fillna(df_t['Event'].mean(), inplace=True)

In [ ]:
df_t['Event'].isnull().sum()

0

In [ ]:
# Separando os targets das features
train_x = df_t.drop(columns=['Alive_X'], axis = 1)
train_y = df_t['Alive_X']

In [ ]:
# Dividindo em treino e teste
train_x, test_x, train_y, test_y = train_test_split(train_x,train_y, test_size = 0.2)

In [ ]:
# Iniciando o treinamento
LR = LinearRegression().fit(train_x, train_y)

In [ ]:
# Fazendo a predição do teste
LR_predict = LR.predict(test_x)

In [ ]:
# Exibindo o percentual de acerto
print("R2 LR:", r2_score(test_y, LR_predict), "\n")

R2 LR: 0.997658408280829